[package]
name = "chain-time"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cfg-if = "1.0"
quickcheck = { version = "0.9", optional = true }
quickcheck_macros = { version = "1.0", optional = true }
chain-ser = { path = "../chain-ser" }
chain-core = { path = "../chain-core" }


[features]
property-test-api = ["quickcheck", "quickcheck_macros"]

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "1.0"