[package]
name = "imhamt"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0"
criterion = { version = "0.3.0", optional = true }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "0.9"

[target.'cfg(unix)'.dev-dependencies]
jemalloc-ctl = "*"
jemallocator = "*"

[features]
default = []
with-bench = ["criterion"]

[[example]]
name = "memdump"
path = "examples/memdump/main.rs"

[[bench]]
harness = false
name = "imhamt"
required-features = ["with-bench"]
