[package]
name = "chain-core"
version = "0.1.0"
authors = ["dev@iohk.io"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
chain-ser = { path = "../chain-ser" }

[dev-dependencies]
quickcheck = "1.0"
